[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
enum-repr = "0.2.6"
rmp-serde = "1.1.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_derive = "1.0"
